version: '3.8'

services:
  ewm-db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: ewm_user
      POSTGRES_PASSWORD: ewm_password
      POSTGRES_DB: ewm_db
    ports:
      - "5432:5432"

  stats-db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: stats_user
      POSTGRES_PASSWORD: stats_password
      POSTGRES_DB: stats_db
    ports:
      - "5433:5432"

#  stats-server:
#    build:
#      context: .
#      dockerfile: stats/stats-server/Dockerfile
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats_db
#      SPRING_DATASOURCE_USERNAME: stats_user
#      SPRING_DATASOURCE_PASSWORD: stats_password
#      SERVER_ADDRESS: 0.0.0.0
#      SERVER_PORT: 9090
#    depends_on:
#      - stats-db
#    ports:
#      - "9090:9090"

  stats-server:
    build:
      context: .
      dockerfile: stats/stats-server/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats_db
      SPRING_DATASOURCE_USERNAME: stats_user
      SPRING_DATASOURCE_PASSWORD: stats_password
      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 9090
    depends_on:
      stats-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/actuator/health || exit 1" ]
      interval: 5s
      retries: 20
      start_period: 5s
    ports:
      - "9090:9090"

#  ewm-service:
#    build:
#      context: .
#      dockerfile: ewm/ewm-service/Dockerfile
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm_db
#      SPRING_DATASOURCE_USERNAME: ewm_user
#      SPRING_DATASOURCE_PASSWORD: ewm_password
#      STATS_SERVER_URL: http://stats-server:9090
#      SERVER_ADDRESS: 0.0.0.0
#      SERVER_PORT: 8080
#    depends_on:
#      - ewm-db
#      - stats-server
#    ports:
#      - "8080:8080"

  ewm-service:
    build:
      context: .
      dockerfile: ewm/ewm-service/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm_db
      SPRING_DATASOURCE_USERNAME: ewm_user
      SPRING_DATASOURCE_PASSWORD: ewm_password
      STATS_SERVER_URL: http://stats-server:9090
      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 8080
    depends_on:
      ewm-db:
        condition: service_healthy
      stats-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health || exit 1" ]
      interval: 5s
      retries: 20
      start_period: 5s
    ports:
      - "8080:8080"