services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    environment:
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stats
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stats"]
      interval: 5s
      retries: 5

  stats-server:
    build:
      context: ./stats/stats-server
      dockerfile: Dockerfile
    container_name: stats-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: stats
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      stats-db:
        condition: service_healthy
    ports:
      - "9090:9090"

  ewm-service:
    build:
      context: ./ewm-service
      dockerfile: Dockerfile
    container_name: ewm-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: stats
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      stats-db:
        condition: service_healthy
    ports:
      - "8080:8080"
