services:

  ewm-service:
    build:
      context: .
      dockerfile: ewm/ewm-service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm_db
      SPRING_DATASOURCE_USERNAME: ewm_user
      SPRING_DATASOURCE_PASSWORD: ewm_password
      STATS_SERVER_URL: http://stats-server:9090
    depends_on:
      - ewm-db
      - stats-server

  stats-server:
    build:
      context: .
      dockerfile: stats/stats-server/Dockerfile
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats_db
      SPRING_DATASOURCE_USERNAME: stats_user
      SPRING_DATASOURCE_PASSWORD: stats_password
    depends_on:
      - stats-db

  ewm-db:
    image: postgres:16
    environment:
      POSTGRES_DB: ewm_db
      POSTGRES_USER: ewm_user
      POSTGRES_PASSWORD: ewm_password
    ports:
      - "5432:5432"

  stats-db:
    image: postgres:16
    environment:
      POSTGRES_DB: stats_db
      POSTGRES_USER: stats_user
      POSTGRES_PASSWORD: stats_password
    ports:
      - "5433:5432"
