
services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    environment:
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stats
    ports:
      - "5433:5432"   # внешний порт : внутренний порт контейнера
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stats"]
      interval: 5s
      retries: 5

  stats-server:
    build: ./stats
    container_name: stats-server
    environment:
      DB_HOST: stats-db
      DB_PORT: 5432
      DB_USER: stats
      DB_PASSWORD: password
      DB_NAME: stats
    depends_on:
      stats-db:
        condition: service_healthy
    ports:
      - "9090:9090"

  ewm-service:
    build: ./ewm-service
    container_name: ewm-service
    environment:
      DB_HOST: stats-db
      DB_PORT: 5432
      DB_USER: stats
      DB_PASSWORD: password
      DB_NAME: stats
    depends_on:
      stats-db:
        condition: service_healthy
    ports:
      - "8080:8080"
