version: '3.9'

services:

  stats-server:
    image: alpine
    command: [ "sh", "-c", "while true; do sleep 1000; done" ]
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    # restart: always
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    ports:
      - "5432:5432"
#     volumes:
#       - ./db-data:/var/lib/postgresql/data

  ewm-service:
    image: alpine
    command: [ "sh", "-c", "while true; do sleep 1000; done" ]
    ports:
      - "8080:8080"

  ewm-db:
    image: alpine
    command: [ "sh", "-c", "while true; do sleep 1000; done" ]
#    image: postgres:16.1
