services:
  ewm_db:
    image: postgres:16.1
    container_name: ewm-db
    environment:
      POSTGRES_USER: ewm_user
      POSTGRES_PASSWORD: ewm_password
      POSTGRES_DB: ewm_db
    ports:
      - "5432:5432"
    networks:
      - ewm_network

  stats_db:
    image: postgres:16.1
    container_name: stats-db
    environment:
      POSTGRES_USER: stats_user
      POSTGRES_PASSWORD: stats_password
      POSTGRES_DB: stats_db
    ports:
      - "5433:5432"
    networks:
      - stats_network

networks:
  ewm_network:
  stats_network:
